### ISSUE TITLE
Problems with e1071::svm

### ISSUE THREAD

**Issue by davbachman** [tbrown122387/gradeR#18] opened 2021-04-16 19:54 UTC
When I use the svm function from the e1071 package, I get a Gradescope error that says `could not find function "isFALSE"` . Any ideas how to fix this?

**Comment by tbrown122387** [comment] 2021-04-16 20:48
Hmm, not sure. Attaching `e1071` with `library(e1071)` doesn't mask the name `isFALSE` because there's no function in that library called `isFALSE`. Are you attaching any other packages? Any other information you can give me? Maybe replacing `isFALSE` with `base::isFALSE` will fix it.

**Comment by davbachman** [comment] 2021-04-17 16:04
I don't have an isFALSE command anywhere, but I am using two other packages: modelr and tidyverse. I've created the simplest possible code to replicate the issue:

`## ------------------------------------------------------------------------
library(tidyverse)
library(modelr)
library(e1071)
test_mod<-svm(Species~.,data=iris)
x<-2
`

The test file for this has a single `test_that` command, to check if x=2. Gradescope gives me the same error: 
`Error in isFALSE(center) : could not find function "isFALSE"
In addition: Warning message:
running command 'timedatectl' had status 1 
[1] "error: isFALSE" "error: center" 
`

**Comment by tbrown122387** [comment] 2021-04-17 16:31
@davbachman can you attach the test file too? Now I suspect that Gradescope's servers have different version of R than your machine does. Maybe just throw in a definition at the top of your test file?

```
isFALSE <- function(x) {
  is.logical(x) && length(x) == 1L && !is.na(x) && !x
}
```

**Comment by tbrown122387** [comment] 2021-08-20 15:35
Closing because this was probably fixed by  #10

**Closed by tbrown122387** 2021-08-20 15:35 UTC

**Comment by davbachman** [comment] 2024-01-29 20:07
Hi Taylor,

Sorry to bother you. I taught with R/Gradescope for several years, but haven’t in a while. I now have a colleague using all my old assignments and autograders. They worked great for him last year but now they stopped.

One line of the setup.sh code that he was using was this:
Rscript -e "install.packages('devtools'); devtools::install_github('tbrown122387/gradeR’)"

That came from an old exchange with you when I was having some trouble implementing something. I don’t know if this line of code is what is now causing issues, but my colleague is getting an error from Gradescope that says “library gradeR not found”.

I had him change the above setup.sh code to this instead:
Rscript -e "install.packages('gradeR')"

And the error changed to:

“Error: library(tidy verse)”
NULL

Any ideas?

Thanks,
Dave

**Comment by tbrown122387** [comment] 2024-01-29 20:54
Hey Dave, 

Feel free to send me the whole zip file he uploads to Gradescope. My guess is he forgot to add a line that installs tidyverse. That doesn't come with `gradeR`. Every third party library will need to be installed on teh gradescope machine, and that gets done in the `setup.sh` file.

**Comment by davbachman** [comment] 2024-01-30 00:24
Hi Taylor,

Thanks for your help! There is a line in the setup file that says:
Rscript -e "install.packages('tidyverse')"

Full zip archive is attached.

Thanks again,
Dave


On Jan 29, 2024, at 12:54 PM, Taylor R. Brown ***@***.***> wrote:



Hey Dave,

Feel free to send me the whole zip file he uploads to Gradescope. My guess is he forgot to add a line that installs tidyverse. That doesn't come with gradeR. Every third party library will need to be installed on teh gradescope machine, and that gets done in the setup.sh file.

**Comment by tbrown122387** [comment] 2024-01-30 18:51
I don't see a zip file

**Comment by davbachman** [comment] 2024-01-30 19:02
Weird! There’s no attachment called “Archive.zip”? Attaching it again here.

Dave



On Jan 30, 2024, at 10:51 AM, Taylor R. Brown ***@***.***> wrote:



I don't see a zip file

**Comment by davbachman** [comment] 2024-01-30 19:22
Is there another email address I can use then?

On Jan 30, 2024, at 11:04 AM, Taylor R. Brown ***@***.***> wrote:



I don't tink Github forwads email attachments to issue attachments. Same issue.

**Comment by davbachman** [comment] 2024-01-30 19:31
Is it better to report this as an issue on GitHub? Maybe I can attach the zip file there.

Thanks,
Dave

On Jan 30, 2024, at 11:04 AM, Taylor R. Brown ***@***.***> wrote:



I don't tink Github forwads email attachments to issue attachments. Same issue.

**Comment by tbrown122387** [comment] 2024-01-30 19:31
Could you open another issue on your computer? There's a button there to add/attach files. 

The reason it should be in a new issue is because this question is coinciding with some difficulties my class is having, and I think I know what the problem is.

**Comment by davbachman** [comment] 2024-01-30 19:45
OK, just created an issue and (hopefully) attached a zip file there. Thanks again for your help!

Dave

On Jan 30, 2024, at 11:31 AM, Taylor R. Brown ***@***.***> wrote:



Could you open another issue on your computer? There's a button there to add/attach files.

The reason it should be in a new issue is because this question is coinciding with some difficulties my class is having, and I think I know what the problem is.
